### ISSUE TITLE
gather feedback and respond accordingly to open merge requests on the core

### ISSUE THREAD

**Issue by macolo** [django-cms/django-cms-mgmt#1]
Message: 
> Hi @philippze thank you very much for this, this looks good, unfortunately django CMS team has been unable to look into this. You might have noticed that we have founded the django CMS Association a month a go and that we are getting more organized. We are also improving the management of incoming PRs... 

- CtA - we would be happy for you to join the dCA (link to info / signup)
- we would love to hear back from you regarding this PR, would you be able to update it / resolve the merge conflicts, so that we can start a review?
- if we dont hear from you within 30 days, we will tentatively close this PR. 

## PRs:
- https://github.com/divio/django-cms/pull/5954 : we like it, keep open, assign to creator, ask to update
- https://github.com/divio/django-cms/pull/6072: we like it, no response from creator, close it tentatively
- https://github.com/divio/django-cms/pull/6380: we like it, is ready for review, assign a reviewer: @Aiky30 
- https://github.com/divio/django-cms/pull/6466: we like it, @Aiky30 will either review it or replace it with a backport PR from v4
- https://github.com/divio/django-cms/pull/6554: we like it, @Aiky30 will review it for release 4
- https://github.com/divio/django-cms/pull/6564: 
- to be completed from https://github.com/divio/django-cms/pulls?page=2&q=is%3Apr+is%3Aopen+sort%3Acreated-asc

## Tasks
- Nicolai to create a spreadsheet with all the PRs
- we ask creators and tech committee members to feed back on what to do (close, fix, review, merge)
- next Friday we collect the feedback and do final decisions
- Nicolai thereafter to leave messages according to decisions taken.

**Comment by NicolaiRidani** [comment]
PR spreadsheet: https://docs.google.com/spreadsheets/d/1GqHqWUJSbjnVb7RNDS3f_o5CofJ6ialz67QZoey3yBU/edit#gid=0

**Comment by NicolaiRidani** [comment]
PR closing message: https://docs.google.com/document/d/1TaJ0dIBuA_8_k2FphOFatNkQjhNSKj9qSFZ_rSEOJj0/edit
