### ISSUE TITLE
create a definition of what changes are required in v4 to switch community efforts to v4 and abandon v3.

### ISSUE THREAD

**Issue by macolo** [django-cms/django-cms-mgmt#2]
- create a definition of what changes are required in v4 to switch community efforts to v4 and abandon v3.
- this was requested by @Aiky30 so the community requirements towards v4 are more clear.

**Comment by Aiky30** [comment]
@macolo I haven't seen an invite in my calendar, have I missed your invite?

**Comment by Aiky30** [comment]
@macolo Pending myself arranging a demonstration with one of the FIL content team members.

**Comment by NicolaiRidani** [comment]
v4 roadmap: https://hackmd.io/5Sj6X5XhTJOmZgNj8e_KCw & v4 project https://github.com/django-cms/django-cms/projects/2

closed
