### ISSUE TITLE
PR process: Amend developer documentation (i.e PR titles must start with one of the categories)

### ISSUE THREAD

**Issue by NicolaiRidani** [django-cms/django-cms-mgmt#68]
Changes to the PR process 

- No need to update CHANGELOG.rst anymore
- information for CHANGELOG.rst release will be directly pulled by the releases script
- Now using conventionalcommits.org guidelines
- scopes already implemented here: https://github.com/django-cms/django-cms/blob/develop/scripts/make-changelog#L10-L16

**Comment by NicolaiRidani** [comment]
https://docs.django-cms.org/en/latest/how_to/contributing.html

**Comment by NicolaiRidani** [comment]
Hi @goutnet this task was assigned to me by the Tech Committee. I am not sure where exactly to add the information about PR nomenclature. 

Would you agree that the best place to inform users on how to name their PR according to our guidelines would be PR template ->https://github.com/django-cms/django-cms/blob/develop/.github/PULL_REQUEST_TEMPLATE.md ? 

Or is this a whole new topic for our documentation? Because afaik we do not have a section about how to create a PR in the documentation. 

thx

**Comment by goutnet** [comment]
Actually, I think we already did that in the 3.9.x template (maybe already
in develop) ?
-- 

Florian Delizy

**Comment by NicolaiRidani** [comment]
> 3.9.x template

could you point me to this template? Thx!

**Comment by NicolaiRidani** [comment]
Ok thx @goutnet
