### ISSUE TITLE
Slack link is invalid

### ISSUE THREAD

**Issue by Bashar** [django-cms/django-cms-mgmt#7]
Visiting the slack link https://django-cmsworkspace.slack.com/join/shared_invite/zt-h21kbeuf-suHBfFMotgNu_H8Esd63Pg#/ listed at https://github.com/django-cms/django-cms-mgmt/blob/master/work%20contribution/work%20groups.md doesn't seem to work

![image](https://user-images.githubusercontent.com/142219/96032811-e5843800-0e67-11eb-87b2-854bed7b81e7.png)

**Comment by NicolaiRidani** [comment]
Interesting. Thx for reporting. For me it does work. I will have a look at it!

**Comment by Bashar** [comment]
@NicolaiRidani including the redirect https://www.django-cms.org/slack which i came to know from your video https://www.youtube.com/watch?v=qqijeEngoaY&feature=youtu.be :)

**Comment by Bashar** [comment]
> Interesting. Thx for reporting. For me it does work. I will have a look at it!

I think it works only from the person who created it, try incognito or another browser/pc/mobile

**Comment by NicolaiRidani** [comment]
https://www.django-cms.org/slack should work now
